# Generated by Django 3.0.5 on 2020-04-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('First_Name', models.CharField(default='infosys', max_length=30, primary_key=True, serialize=False)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
                ('Username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(max_length=100)),
                ('Created_at', models.DateField()),
                ('Updated_at', models.DateField()),
                ('user', models.ForeignKey(default='infosys', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.user')),
            ],
        ),
    ]
