# Generated by Django 3.0.5 on 2020-04-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.CharField(default='1', max_length=30, primary_key=True, serialize=False),
        ),
    ]
