# Generated by Django 3.0.5 on 2020-04-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='db_app1',
        ),
    ]
